language: python
python:
    - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - echo PYTHONPATH=`pwd`
  - nosetests --with-coverage tests/ --cover-package=app --cover-xml --cover-erase

after_success:
  - coveralls
